#!/bin/bash
clear

HOSTNAME=$(hostname)
ID=$(id -u)

[ "$HOSTNAME" != "LServer" ] && echo "THIS SCRIPT SHOULD ONLY BE RAN ON THE MAIN SERVER!" && sleep 2 && exit
[ "$ID" -eq 0 ] && echo "THIS SCRIPT SHOULD NOT BE RAN AS ROOT!" && sleep 2 && exit

#CHECK IF IN TMUX SESSION Barcode
[ "$1" == '--front' ] && tmux a -t "FrontCounter:menu" 2>/dev/null || tmux new-session -s "FrontCounter" $0 \; rename-window "menu" \; set mouse on \; 2>/dev/null
[ "$1" == '--jon' ] && tmux a -t "JON:menu" 2>/dev/null || tmux new-session -s "Jon" $0 \; rename-window "menu" \; set mouse on \; 2>/dev/null
[ ! "$TMUX" ] && tmux a -t "BarcodeMenu:menu" 2>/dev/null || tmux new-session -s "BarcodeMenu" $0 \; rename-window "menu" \; set mouse on \; 2>/dev/null
[ ! "$TMUX" ] && exit
############################################# FUNCTIONS ###################################################

function option_picked() {
	COLOR='\033[01;31m' # bold red
	RESET='\033[00;00m' # normal white
	MESSAGE=${@:-"${RESET}Error: No message passed"}
	echo -e "${COLOR}${MESSAGE}${RESET}"
}

function c_timestamp() {
	date | awk '{print $2,$3,$4}'
}

function display_banner() {
echo -e "${BANNER} __                   __                  "
echo "/__ |  _ |_  _  |    /   _ __ __  _ __  _|"
echo "\_| | (_)|_)(_| |    \__(_)||||||(_|| |(_|"
echo -e "${NORMAL}"
}
############################################# PRECHECKS AND VARIABLES #################################################

BANNER=`echo "\033[1;37m"`
NORMAL=`echo "\033[m"`
MENU=`echo "\033[36m"` #Blue
MENUITEM=`echo "\033[1;36m"` #BrightBlue
NUMBER=`echo "\033[33m"` #yellow
FGRED=`echo "\033[41m"`
RED_TEXT=`echo "\033[31m"`
ENTER_LINE=`echo "\033[1;32m"` #bright green
INFO=`echo "\033[1;34m"` #blue
MENUTITLE=`echo "\033[1;35m"` #Bright Pink

############################################### MENUS ####################################################

main_menu(){
	clear
	display_banner
	echo -e "${MENU}***********************************************************************${NORMAL}"
	echo -e "${MENUTITLE}  ************************* CHECK-IN MENU **************************${NORMAL}"
	echo -e "${MENU}***********************************************************************${NORMAL}"
	echo -e "${MENU}**${NUMBER} 1)${MENUITEM} Check-In Computer ${NORMAL}"
	echo -e "${MENU}**${NUMBER} 2)${MENUITEM} Check Out Computer ${NORMAL}"
	echo -e "${MENU}**${NUMBER} 3)${MENUITEM} Change Computer Status ${NORMAL}"
	echo -e "${MENU}**${NUMBER} 4)${MENUITEM} Check Computer Report ${NORMAL}"
	echo -e "${MENU}**${NUMBER} 5)${MENUITEM} Change Customer Info and Notes ${NORMAL}"
	echo -e "${MENU}**${NUMBER} 6)${MENUITEM} Check Status Tracker ${NORMAL}"
	echo -e "${MENU}**${NUMBER} 7)${MENUITEM} Make a Note On a Checked-In PC ${NORMAL}"
	echo -e "${MENU}**${NUMBER} 8)${MENUITEM} Search For an Archived Check-In ${NORMAL}"
	echo -e "${MENU}**${NUMBER} 9)${MENUITEM} Manually change IDCOUNT number ${NORMAL}"
	echo -e "${MENU}**${NUMBER} 10)${MENUITEM} Reprint check-in sheet (Work In Progress) ${NORMAL}"
	echo -e "${MENU}**${NUMBER} 11)${MENUITEM} List info files in Other folder ${NORMAL}"
	echo -e "${MENU}**${NUMBER} 98)${MENUITEM} Delete PCID Folder (DANGEROUS) ${NORMAL}"
	echo -e "${MENU}**${NUMBER} 99)${MENUITEM} Delete Customer Folder (DANGEROUS) ${NORMAL}"
	echo -e "${MENU}***********************************************************************${NORMAL}"
	echo -e "${ENTER_LINE}Please enter a menu option. ${NORMAL}"
	read -p ': ' optMain

while [ optMain != '' ]
do
	case $optMain in
    	1) clear;
	        tmux new-window -n Check-In ./Files/chkIn.sh;
		main_menu;
        	;;

        2) clear;
	        tmux new-window -n Check-Out ./Files/chkOut.sh;
		main_menu;
		;;

        3) clear;
	        tmux new-window -n ChangePCStatus ./Files/chgStatus.sh;
		main_menu;
		;;

    	4) clear;
	        tmux new-window -n CheckPCStatus ./Files/chkStatus.sh;
		main_menu;
            	;;

	5) clear;
	        tmux new-window -n ChangeCustomerInfo ./Files/chgCusInfo.sh;
		main_menu;
            	;;

	6) clear;
	        tmux new-window -n StatusTracker ./Files/statusTracker.sh;
		main_menu;
            	;;

	7) clear;
	        tmux new-window -n MakeNote ./Files/mkNote.sh;
		main_menu;
            	;;

	8) clear;
	        tmux new-window -n SearchArchives ./Files/searchArchive.sh;
		main_menu;
            	;;

	9) clear;
		tmux new-window -n ChangeIDCOUNT "nano ./Files/CustomerLogs/.IDCOUNT";
		main_menu;
            	;;

	10) clear;
		main_menu;
            	;;

	11) clear;
		tmux new-window -n SearchOther ./Files/findOther.sh;
		main_menu;
		;;

	98) clear;
		tmux new-window -n DeletePCID ./Files/delPCID.sh;
		main_menu;
            	;;

	99) clear;
		tmux new-window -n DeleteCustomer ./Files/delCustomer.sh;
		main_menu;
            	;;

        *)clear;
        	main_menu;
        	;;
    esac
done


}

main_menu
